# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "vmd" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c5dceb70-e086-4e8b-950a-3723b1ce0817";
      fsType = "btrfs";
      options = [ "subvol=nixos/@" "compress=zstd" "ssd" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/6d789dd8-bfb3-4cdf-adf4-5544f4e7fa8b";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c5dceb70-e086-4e8b-950a-3723b1ce0817";
      fsType = "btrfs";
      options = [ "subvol=nixos/@nix" "compress=zstd" "ssd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/nvme0n1p6"; #p4
      fsType = "btrfs";
      options = [ "subvol=nixos" "compress=zstd" "ssd" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/DE88-501C";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c5dceb70-e086-4e8b-950a-3723b1ce0817";
      fsType = "btrfs";
      options = [ "subvol=nixos/@home" "compress=zstd" "ssd" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
